version: '2'
services:
  web:
    image: odoo:10
    depends_on:
      - db
    ports:
      - "8020:8069"
    volumes:
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo